## ğŸš€ Features

- ğŸ” JWT-based authentication
- ğŸ‘¥ User registration and login
- ğŸ›¡ï¸ Protected routes with middleware
- ğŸ§© MVC-style structure for easy scalability

## ğŸ› ï¸ Tech Stack

- **Backend:** Node.js, Express.js
- **Database:** MongoDB (with Mongoose)
- **Auth:** JSON Web Token (JWT)
- **Middleware:** Custom Auth Middleware

## âš™ï¸ Setup Instructions :- 

### Clone the Repository

```bash
git clone https://github.com/sajal-pakira/Food-App.git
cd Food-App
